### ISSUE TITLE
In IOS devices, when try to write to a Iso15693 tag, getting 'Stack error'. 

### ISSUE THREAD

**Issue by ishwaryamamidi** [okadan/flutter-nfc-manager-app#2]
I tried to test this example app to write to 'tagV, but unfortunately it throws an error saying 'Stack error'. Is there any way to solve this problem?

Steps Followed (Only IOS):
Launch app -> Ndef Write -> Add record -> Added a record of type 'Text' -> Start scan -> Error message (Stack error).

**Comment by okadan** [comment]
@ishwaryamamidi I think that writing to tags that are not NDEF formatted may not be allowed on iOS.
